@api = http://localhost:3000/api

GET {{api}}/teacher
    # ?types=courses
    # ?types=course-one
    ?types=sessions
    &url=a-10
###
@api = http://localhost:3000/api
GET {{api}}/teacher/64a1abab923f2f3e96302420
###
@api = http://localhost:3000/api
POST  {{api}}/teacher/64a1abab923f2f3e96302420/add-session
content-type: application/json

{
          "title":"test session 4",
           "time_start":"16:30",
           "date_start":"2023/7/20"
}
###
@api = http://localhost:3000/api
GET  {{api}}/teacher/64a1abab923f2f3e96302420/64acf9b68ffcb4489cf184ce
###
@api = http://localhost:3000/api
DELETE   {{api}}/teacher/64a1abab923f2f3e96302420/64ac66b12f8792dcfe11ebd7
###
GET http://localhost:3000/api/courses/64a9a12aeca3fa0f2a8bf1d7/student?phone=77&name=
###
@api = http://localhost:3000/api
PUT  {{api}}/auth 
content-type: application/json

{
          "email":"ktsyr1@gmail.com",
           "password":"0000"
}
###
@api = http://localhost:3000/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt0c3lyMUBnbWFpbC5jb20iLCJfaWQiOiI2NGQ5ZmZkZWIzNzdlZTVkZjUzNmJhMGIiLCJpYXQiOjE2OTg2ODUxMzV9._hPdT6bUKdnegmGmdPkaLwWeMjZU0jk7Xa6nCYnZCR4
POST   {{api}}/teacher/64ca1ec3474ef93ba181a754/0
content-type: application/json
token: {{token}}
{ 
    "course_id": "64ca1ec3474ef93ba181a754",
    "title": "الجلسة 2",
    "time_start": "12:59",
    "date_start": "2023-08-23",
    "completion": true
}
###
@api = http://localhost:3000/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt0c3lyMUBnbWFpbC5jb20iLCJfaWQiOiI2NGQ5ZmZkZWIzNzdlZTVkZjUzNmJhMGIiLCJpYXQiOjE2OTg2ODUxMzV9._hPdT6bUKdnegmGmdPkaLwWeMjZU0jk7Xa6nCYnZCR4
GET   {{api}}/teacher/64ca1ec3474ef93ba181a754/
content-type: application/json
token: {{token}}

HTTP/1.1 308  - Permanent Redirect
location: /api/teacher/64ca1ec3474ef93ba181a754
refresh: 0;url=/api/teacher/64ca1ec3474ef93ba181a754
date: Mon, 30 Oct 2023 19:54:05 GMT
connection: close
transfer-encoding: chunked
###
@api = http://localhost:3000/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt0c3lyMUBnbWFpbC5jb20iLCJfaWQiOiI2NGQ5ZmZkZWIzNzdlZTVkZjUzNmJhMGIiLCJpYXQiOjE2OTg2ODUxMzV9._hPdT6bUKdnegmGmdPkaLwWeMjZU0jk7Xa6nCYnZCR4
GET   {{api}}/courses/64ca1ec3474ef93ba181a754/
content-type: application/json
token: {{token}} 

HTTP/1.1 308  - Permanent Redirect
location: /api/courses/64ca1ec3474ef93ba181a754
refresh: 0;url=/api/courses/64ca1ec3474ef93ba181a754
date: Mon, 30 Oct 2023 17:52:09 GMT
connection: close
transfer-encoding: chunked